<template>
    <div>
        <transition name="swing">
            <div v-if="showFixedNavbar" class="fixed w-full bg-mtw-primary text-mtw-text bg-opacity-50 shadow-lg z-40" style="background-color: #7FACBF">
                <NavbarContent @disableNavbar="toggleDisable" ref="navbarcontent" :show-fixed-navbar="showFixedNavbar"></NavbarContent>
            </div>
        </transition>
    </div>
</template>

<script>
import NavbarContent from "./NavbarContent";

export default {
    name: "FixedNavbar",
    components: {NavbarContent},
    data() {
        return {
            showFixedNavbar: false,
            disableFixedNavbar:false,
        }
    },
    mounted() {
        this.toggleFixedNavbar();
    },
    methods: {
        toggleFixedNavbar() {
            const heightOfNavbar = 100;
            document.addEventListener('scroll', () => {
                if (!this.disableFixedNavbar){
                    this.showFixedNavbar = window.scrollY > heightOfNavbar;
                }
            })
        },
        toggleDisable(){
            console.log('toggled navbar')
            this.disableFixedNavbar=!this.disableFixedNavbar;
        }
    }
}
</script>

<style scoped>
.swing-enter-active {
    -webkit-animation: swing-in-top-fwd 2s cubic-bezier(0.175, 0.885, 0.320, 1.275) both;
    animation: swing-in-top-fwd 2s cubic-bezier(0.175, 0.885, 0.320, 1.275) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2021-9-6 19:40:57
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation swing-in-top-fwd
 * ----------------------------------------
 */
@-webkit-keyframes swing-in-top-fwd {
    0% {
        -webkit-transform: rotateX(-100deg);
        transform: rotateX(-100deg);
        -webkit-transform-origin: top;
        transform-origin: top;
        opacity: 0;
    }
    100% {
        -webkit-transform: rotateX(0deg);
        transform: rotateX(0deg);
        -webkit-transform-origin: top;
        transform-origin: top;
        opacity: 1;
    }
}

@keyframes swing-in-top-fwd {
    0% {
        -webkit-transform: rotateX(-100deg);
        transform: rotateX(-100deg);
        -webkit-transform-origin: top;
        transform-origin: top;
        opacity: 0;
    }
    100% {
        -webkit-transform: rotateX(0deg);
        transform: rotateX(0deg);
        -webkit-transform-origin: top;
        transform-origin: top;
        opacity: 1;
    }
}

</style>
